// GENERATED by scripts/generate-manifests.mjs — do not edit by hand.
// The skill is the distributed unit and does not ship package.json, so the
// version has to live inside it. `npm run generate-manifests` regenerates this
// from package.json; `npm test` fails if it has drifted.
export const VERSION = "0.1.0";
